apps:
  - script   : ./index.js
    name     : 'Stranger_things'
    instances: 2
    exec_mode: cluster
    watch    : false
    max_memory_restart: '200M'
  # - script : ./worker.js
  #   name   : 'worker-app'
  #   watch  : true
  #   env    :
  #     NODE_ENV: development
  #   env_production:
  #     NODE_ENV: production