apps:
  name: tandyfw-bd
  script: ./index.js
  exec_mode: cluster
  instances: 2
  max_memory_restart: 200M
  env_heroku:
    PORT: 3000
    UPSIDEDOWN_MODE: true
  name: tandyfw-bk
  script: ./index.js
  exec_mode: cluster
  instances: 2
  max_memory_restart: 200M
  env_heroku:
    PORT: 3000
    UPSIDEDOWN_MODE: true