# rodar o '$ pm2 ecosystem' e criar o ambiente; em formato yml parece ficar mais 'limpo' e legível que em config.js;
 apps:
  - script   : ./index.js
    name     : 'JRGCast-stranger-things'
    instances: 2
    exec_mode: cluster
    max_memory_restart: '200M'
    watch  : false
    env    :
      PORT: 3000
    #   NODE_ENV: development
    # env_production:
    #   NODE_ENV: production
