apps:
  - name: stranger-things
    script: ./index.js
    watch: false
    exec_mode: cluster
    instances: 2
    max_memory_restart: 200M
    env_hawkins:
      PORT: 3000
      UPSIDEDOWN_MODE: false
    env_upside-down:
      PORT: 3000
      UPSIDEDOWN_MODE: true