apps:
- name: app
  script: ./index.js
  exec_mode: cluster
  instances: 2
  watch: false
  max_memory_restart: 200M
  env_heroku:
    UPSIDEDOWN_MODE: false
  env_bidfca-bd:
    UPSIDEDOWN_MODE: true