# rodar o '$ pm2 ecosystem' e criar o ambiente; em formato yml parece ficar mais 'limpo' e legível que em config.js;
 apps:
  - script   : ./index.js
    name     : 'JRGCast-stranger-things'
    instances: 2
    exec_mode: cluster
    max_memory_restart: '200M'
    watch  : false
    env    :
      NODE_ENV: 'development'
      UPSIDEDOWN_MODE: false
      PORT: 3000
    env_test :
      NODE_ENV: 'test'
      UPSIDEDOWN_MODE: false
      PORT: 3100
    # env_production:
    #   NODE_ENV: production
